name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8

  # The basics
  - numpy
  - pandas
  - scipy

  # Development
  - awscli
  - black
  - dvc
  - python-language-server
  - pre-commit
  - jupyterlab
  - jupyterlab-git>=3.0.0

  # Machine-learning
  - scikit-learn
  - tensorflow-gpu=2.2
  - xgboost
  
  # Plotting
  - matplotlib
  - plotly::plotly
  - plotly::python-kaleido

  # Pip
  - pip
  - pip:
      - wandb
      - virtualenv==20.0.23 # pre-commit doesn't work with default version
      - -e .
